version: '3'
services:
  sk-ng16:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:4200"  # Map your local port to the container's port
    volumes:
      - .:/app       # Mount your local project directory into the container
    command: tail -F /dev/null